### ISSUE TITLE
When will the video-lavit code be released?

### ISSUE THREAD

**Issue by howardgriffin** [jy0205/LaVIT#12]

**Comment by jy0205** [comment]
Yes, the model and code will be released in the next few weeks.

**Comment by ChenyangQiQi** [comment]
Congratulations on your research. The same question; look forward to the release of the video model!

**Comment by ninjasaid2k** [comment]
This project looks amazing , hope to see the video generation

**Comment by jianlong-yuan** [comment]
Are you ready ?

**Comment by jy0205** [comment]
> Are you ready ?

Thanks for your attention. We plan to release the Video-LaVIT in the next two weeks.

**Comment by xizaoqu** [comment]
> Thanks for your attention. We plan to release the Video-LaVIT in the next two weeks.

Thanks, really looking forward to it :)

**Comment by Luyitas** [comment]
Impressive work, looking forward to the code release

**Comment by advenTure423** [comment]
> > Are you ready ?
> 
> Thanks for your attention. We plan to release the Video-LaVIT in the next two weeks.

Hi, any update for the release?

**Comment by jy0205** [comment]
> > > Are you ready ?
> > 
> > 
> > Thanks for your attention. We plan to release the Video-LaVIT in the next two weeks.
> 
> Hi, any update for the release?

Soon, we are cleaning up the code and will release within this week.

**Comment by advenTure423** [comment]
> Soon, we are cleaning up the code and will release within this week.

That's cool!

**Comment by devin12422** [comment]
Im excited for sure. Might be time for me to hunker down and process this paper
