### ISSUE TITLE
Motion Vectors Dataloading

### ISSUE THREAD

**Issue by PardoAlejo** [jy0205/LaVIT#13]
Hi,

Thank you for sharing this remarkable work. I noticed that there are currently no plans to release the training code. Nonetheless, I was wondering if it might be possible for you to provide a **simplified version of your data loader.** Specifically, a version that includes the **extraction of keyframes and motion vectors would be incredibly helpful**. 
It's understandable if the complete training data loader cannot be shared; a minimal working example would be greatly appreciated.

Thank you for considering this request!

**Comment by jy0205** [comment]
The data loader code will be released in the next few weeks. By the way, we use this tool: https://github.com/LukasBommes/mv-extractor to extract motion vectors.
