### ISSUE TITLE
annotation for InterVid-14M-aesthetics

### ISSUE THREAD

**Issue by dreamerlin** [jy0205/LaVIT#14]
![image](https://github.com/jy0205/LaVIT/assets/33949370/b97f4d03-43ae-4c08-a276-eb64ceceebd0)
Thanks for your great work! Could you please provide the annotation for the filtered InterVid-14M-aesthetics, which is used for removing the watermarks of webvid10m

**Comment by feifeiobama** [comment]
The InternVid-14M-aesthetics subset can be downloaded from https://huggingface.co/datasets/OpenGVLab/InternVid/tree/4d3c6df.
