### ISSUE TITLE
Question about CIDEr score

### ISSUE THREAD

**Issue by dusruddl2** [jy0205/LaVIT#15]
Hello,
Thanks for your outstanding work!

I used Flickr dataset to get the CIDEr score, but I got 67, not 83 as mentioned in the paper.

1. Was there a data preprocessing for the case of image captions being too short or too long? Or did you use all the data?
2. Can you share the code you used when getting the CIDEr score?

+ These are dataset and CIDEr score code that I used
https://www.kaggle.com/datasets/hsankesara/flickr-image-dataset/data
https://github.com/tylin/coco-caption/tree/master/pycocoevalcap/cider

**Comment by jy0205** [comment]
Hi, We report the CIDEr score on the test set of Flickr dataset (NOT all the data) following the existing methods (e.g., blip2, kosmos, etc), which contains about 1k samples.

**Comment by dusruddl2** [comment]
Thanks for your reply! I'll use the set of Flickr :)
