### ISSUE TITLE
How much graphics memory is required to use the latest weights to generate text images? (Mine is 3060, 12G, unable to load model weights at all)

### ISSUE THREAD

**Issue by shams2023** [jy0205/LaVIT#18]
How much graphics memory is required to use the latest weights to generate text images? (Mine is 3060, 12G, unable to load model weights at all)

**Comment by jy0205** [comment]
It requires at least 22GB to load the model.

**Comment by shams2023** [comment]
> 它至少需要 22GB 来加载模型。

Is there an int8 weight?

**Comment by jy0205** [comment]
We don't have that yet
