### ISSUE TITLE
RuntimeError: expected scalar type Float but found BFloat16

### ISSUE THREAD

**Issue by patrick-tssn** [jy0205/LaVIT#24]
Following this environment setting: https://github.com/jy0205/LaVIT/tree/main/VideoLaVIT#requirements, when running this script: https://github.com/jy0205/LaVIT/blob/main/VideoLaVIT/understanding.ipynb, I encounter this Error.

![image](https://github.com/jy0205/LaVIT/assets/38104831/0d1409ac-7a55-463f-96c1-443875d6c214)

Could you please reassure the environment?

**Comment by patrick-tssn** [comment]
I've implemented a temporary solution: in the files modeling_visual_encoder.py, modeling_visual_tokenizer.py, and modeling_motion_tokenizer.py, I modified the LayerNorm function to use torch.bfloat16 instead of torch.float32. This adjustment is effective for inference; however, I am uncertain about its compatibility with the training pipeline. I look forward to your feedback on this matter.

**Comment by jy0205** [comment]
Thank you for identifying this potential issue when the apex is not installed. We use the fusedlayernorm in apex during training. Your temporal solution is right.
