### ISSUE TITLE
[Video-LaVIT] Objective function of the Tokenizers, Key Frame Detokenizer and Motion Condition Encoder

### ISSUE THREAD

**Issue by Hesh0629** [jy0205/LaVIT#33]
Hello,

Thank you for the excellent paper and for releasing the code.

While reading the paper, I noticed that the training objectives for the 
**_image and motion tokenizers_**,
**_key frame detokenizer_**, 
and **_motion condition encoder_** seemed to be missing.

Could you describe the training objectives for these modules?

**Comment by jy0205** [comment]
The training objectives keyframe tokenizer / de-tokenizer are detailed in the LaVIT paper: https://arxiv.org/abs/2309.04669. (The Eq 4 and 5). The training objective for motion tokenizer is reconstruction loss (MSE) like VQVAE.

**Comment by Hesh0629** [comment]
Thank you for your answer! I think my question is resolved.

**Comment by Hesh0629** [comment]
Thank you for your answer! I think my question is resolved.
