### ISSUE TITLE
Question about ViT

### ISSUE THREAD

**Issue by SihengLi99** [jy0205/LaVIT#7]
Hi,

Wonderful work!
A question about the version of the ViT-G/14 of EVA-CLIP.
Could you please give some details about it? Where is it from? Could you please release the code for building this ViT from the original open-sourced weights?
Thanks a lot!

Sincerely

**Comment by jy0205** [comment]
We use the same code from the original EVA-CLIP repo (only using the EVA-ViT). Please see https://github.com/baaivision/EVA/blob/master/EVA-CLIP/rei/eva_clip/model.py for more details.

**Comment by SihengLi99** [comment]
Hi,

There are so many EVA-CLIP versions at
https://github.com/baaivision/EVA/tree/master/EVA-CLIP.
Could you please tell me which version is used?

Thanks!

jy0205 ***@***.***> 于2023年11月19日周日 20:32写道：

**Comment by jy0205** [comment]
We use the  EVA-01-CLIP Series, the model name is EVA01_CLIP_g_14_plus_psz14_s11B. It can be downloaded from https://huggingface.co/QuanSun/EVA-CLIP/blob/main/EVA01_CLIP_g_14_plus_psz14_s11B.pt

**Comment by SihengLi99** [comment]
OK, Thanks for your quick response, It is very helpful!

jy0205 ***@***.***> 于2023年11月20日周一 17:49写道：
