### ISSUE TITLE
Issues running the model

### ISSUE THREAD

**Issue by andysingal** [jy0205/LaVIT#8]
Thanks for sharing this model.

I am having the following issues while running the model: https://huggingface.co/rain1011/LaVIT-7B-v2/discussions/1 

I am using the following notebook when running the model: https://github.com/jy0205/LaVIT/blob/main/multimodal_synthesis.ipynb

Looking forward to hearing from you.
Thanks,
Andy

**Comment by jy0205** [comment]
Hi! You can set use_xformers=False, this error is raised because you do not install the xformers in your environment
